MODEL:
    NUM_CLASSES: 5
    BACKBONE:
        NAME: 'basic'
        PRETRAINED: False
        OUT_CHANNELS: [512, 1024, 512, 256, 128, 64]
        INPUT_CHANNELS: 3 # from the pre-trained ResNet50
    PRIORS:
        FEATURE_MAPS: [512, 1024, 512, 256, 128, 64]
INPUT:
    IMAGE_SIZE: 300
DATASETS:
    TRAIN: ("waymo_train",)
    TEST: ("waymo_val", )
SOLVER:
    MAX_ITER: 5000
    LR_STEPS: [80000, 100000]
    GAMMA: 0.1
    BATCH_SIZE: 16
    LR: 1e-3
OUTPUT_DIR: 'outputs/waymo'
DATASET_DIR: '/work/datasets'
EVAL_STEP: 1000
MODEL_SAVE_STEP: 1000
LOG_STEP: 100
