MODEL:
    NUM_CLASSES: 5
    BACKBONE:
        NAME: 'resnet'
        PRETRAINED: False
        OUT_CHANNELS: [256, 512, 512, 256, 256, 256]
        INPUT_CHANNELS: 3
    PRIORS:
        FEATURE_MAPS: [[40, 30], [20, 15], [10, 8], [5, 4], [3, 2], [3, 2]]
        STRIDES: [[8, 8], [16, 16], [27, 27], [40, 40], [80, 80], [320, 240]]
INPUT:
    IMAGE_SIZE: [320, 240]
DATASETS:
    TRAIN: ("waymo_train",)
    TEST: ("waymo_val", )
DATA_LOADER:
    NUM_WORKERS: 4
SOLVER:
    MAX_ITER: 25000
    LR_STEPS: [80000, 100000]
    GAMMA: 0.1
    BATCH_SIZE: 16
    LR: 1e-3
OUTPUT_DIR: 'outputs/waymo_resnet'
DATASET_DIR: "/work/datasets"
EVAL_STEP: 1500
MODEL_SAVE_STEP: 1500
LOG_STEP: 500
